# Generated by Django 4.2.16 on 2024-09-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_hub', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
        migrations.AlterField(
            model_name='post',
            name='blurb',
            field=models.TextField(blank=True),
        ),
    ]
