# Generated by Django 4.2.16 on 2024-09-23 16:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_hub', '0004_alter_vote_post'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'comment'), ('user', 'post')},
        ),
    ]
