# Generated by Django 4.2.16 on 2024-11-19 18:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_hub', '0011_comment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner_image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dbbqdfomn/image/upload/v1732040135/default.jpg', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='group_image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dbbqdfomn/image/upload/v1732040135/default.jpg', max_length=255, verbose_name='image'),
        ),
    ]
