# Generated by Django 4.2.16 on 2024-11-23 20:56

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_hub', '0013_update_default_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birthdate',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dbbqdfomn/image/upload/v1732040135/default_profile.jpg', max_length=255, verbose_name='image'),
        ),
    ]
