# Generated by Django 4.2.16 on 2024-11-29 14:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_hub', '0014_remove_profile_birthdate_profile_is_private_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dbbqdfomn/image/upload/v1732040135/default_profile.png', max_length=255, verbose_name='image'),
        ),
    ]
